apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hpa-example
spec:
    replicas: 3
    template:
        metadata:
            name: hpa-example
            labels:
                app: hpa-example
        spec:
            containers:
            - name: hpa-example
              image: gcr.io/google_containers/hpa-example
              ports:
              - name: http-port
                containerPort: 80
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: hpa-example-svc
spec:
    type: LoadBalancer
    selector:
        app: hpa-example
    ports:
    - port: 31001
      nodePort: 31001
      targetPort: http-port
      protocol: TCP
